application: ambienators-ipeech2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

- url: /simplex
  static_dir: simplex

- url: /.*
  script: ambienators-nus.app

- url: /templates
  script: ambienators-nus.app
  login: required


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

