application: ambienators-nus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /simplex
  static_dir: simplex

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

- url: /
  script: ambienators-nus.app

- url: /arduinopost
  script: ambienators-nus.app

- url: /.*
  script: ambienators-nus.app
  login: required


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

